######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 13 10:22:52 2011
######################################################################

TEMPLATE = app
TARGET = cryptogram

# Input
QT += widgets printsupport
SOURCES += main.cpp cryptogram.cpp
HEADERS += cryptogram.h cryptogramui.h

